#!/usr/bin/env zsh
# Non-interactive-ish helper to push the current workspace to the provided GitHub repo via SSH.
# Usage:
#   ./scripts/push_via_ssh.sh "Commit message here"
# If no commit message is provided, an autogenerated message is used.

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_ROOT"

SSH_REMOTE="git@github.com:ennmahmud/preventive-health-assistant.git"

# Create a backup zip (safe default)
backup="$PROJECT_ROOT/preventive-health-assistant-backup-$(date +%Y%m%dT%H%M%S).zip"
if command -v zip >/dev/null 2>&1; then
  echo "Creating backup: $backup"
  zip -r "$backup" . >/dev/null
  echo "Backup created."
else
  echo "zip not found; skipping automatic backup. Install zip (brew install zip) if you want backups."
fi

# Ensure inside a git repo
if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "No git repository found in $PROJECT_ROOT"
  echo "Initializing a new git repository..."
  git init
fi

# Check current branch
branch=$(git branch --show-current || echo "main")
if [[ -z "$branch" ]]; then
  branch="main"
fi
echo "Using branch: $branch"

# Ensure there is at least one commit (if empty repo, make initial commit)
if ! git rev-parse --verify HEAD >/dev/null 2>&1; then
  echo "Repository has no commits. Creating an initial empty commit to bootstrap history."
  git commit --allow-empty -m "chore: initial commit"
fi

# Check SSH connectivity to GitHub
echo "Checking SSH authentication to github.com..."
ssh_output=$(ssh -T git@github.com 2>&1 || true)
if echo "$ssh_output" | grep -qi "successfully authenticated"; then
  echo "SSH authentication to GitHub looks good."
else
  echo "SSH test output:"
  echo "$ssh_output"
  echo "\nUnable to verify SSH authentication to GitHub."
  echo "Please ensure your SSH key is added to the ssh-agent and to your GitHub account."
  echo "See: https://docs.github.com/en/authentication/connecting-to-github-with-ssh"
  exit 1
fi

# Stage all changes
echo "Staging all changes..."
git add -A

# Commit if there are staged changes
if git diff --staged --quiet; then
  echo "No staged changes to commit."
else
  commit_msg="${1:-"chore: update workspace $(date -u +%Y-%m-%dT%H:%M:%SZ)"}"
  git commit -m "$commit_msg"
  echo "Committed: $commit_msg"
fi

# Configure remote origin to the SSH URL
if git remote get-url origin >/dev/null 2>&1; then
  echo "Setting origin to $SSH_REMOTE"
  git remote set-url origin "$SSH_REMOTE"
else
  echo "Adding origin $SSH_REMOTE"
  git remote add origin "$SSH_REMOTE"
fi

# Fetch and push
echo "Fetching from origin..."
git fetch origin --prune || true

echo "Pushing branch $branch to origin..."
if git push -u origin "$branch"; then
  echo "Push succeeded."
else
  echo "Push failed. You likely have divergent remote history."
  echo "Suggestions (pick one manually):"
  echo "  1) Merge remote: git pull --no-rebase origin $branch && git push origin $branch"
  echo "  2) Rebase onto remote: git pull --rebase origin $branch && git push origin $branch"
  echo "  3) Force update (use carefully): git push --force-with-lease origin $branch"
  exit 1
fi

# Final verification
echo "\nRemote heads for origin:" 
git ls-remote --heads origin

echo "Done. If you need further help (for example to rebase, resolve conflicts, or force push), run the interactive script: ./scripts/push_changes.sh"
