#!/usr/bin/env zsh
# Interactive safe push script for macOS zsh
# Usage: ./scripts/push_changes.sh

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_ROOT"

echo "Project root: $PROJECT_ROOT"

default_backup="$PROJECT_ROOT/preventive-health-assistant-backup-$(date +%Y%m%dT%H%M%S).zip"

read -r -p "Create a zip backup of the workspace? [Y/n]: " create_backup
create_backup=${create_backup:-Y}
if [[ "$create_backup" =~ ^([yY][eE][sS]|[yY])$ ]]; then
  if command -v zip >/dev/null 2>&1; then
    echo "Creating backup: $default_backup"
    zip -r "$default_backup" . >/dev/null
    echo "Backup created: $default_backup"
  else
    echo "zip not found; skipping backup. To install: brew install zip"
  fi
else
  echo "Skipping backup as requested."
fi

# Check if this is a git repo
if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "No git repository found in $PROJECT_ROOT"
  read -r -p "Initialize a new git repository here? [y/N]: " init_git
  init_git=${init_git:-N}
  if [[ "$init_git" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    git init
    echo "Git repo initialized."
  else
    echo "Aborting. Initialize a git repository and run this script again."
    exit 1
  fi
fi

# Show current state
current_branch=$(git branch --show-current || echo "(detached or none)")
echo "Current branch: $current_branch"

git remote -v || true

echo "Recent commits:"
git --no-pager log --oneline -n 5 || true

# Show uncommitted changes
echo "\nWorking tree status (porcelain):"
git status --porcelain

default_branch="$current_branch"
read -r -p "Switch or create a branch? Enter branch name (leave empty to keep '$default_branch'): " target_branch
if [[ -n "$target_branch" ]]; then
  if git show-ref --verify --quiet refs/heads/$target_branch; then
    git switch "$target_branch"
  else
    git switch -c "$target_branch"
  fi
  echo "Now on branch: $(git branch --show-current)"
fi

# Stage changes
echo "\nStaging changes..."
read -r -p "Stage all changes? [Y/n]: " stage_all
stage_all=${stage_all:-Y}
if [[ "$stage_all" =~ ^([yY][eE][sS]|[yY])$ ]]; then
  git add -A
else
  echo "You can stage changes manually and re-run this script. Exiting."
  exit 1
fi

# Commit
if git diff --staged --quiet; then
  echo "No staged changes to commit."
else
  echo "Recommended commit message format: type(scope): short summary\nExample: fix(api): correct user validation\n"
  read -r -p "Commit message (single-line or empty to use autogenerated): " commit_msg
  if [[ -z "$commit_msg" ]]; then
    autogenerated="chore: update workspace $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    git commit -m "$autogenerated"
    echo "Created commit with message: $autogenerated"
  else
    git commit -m "$commit_msg"
    echo "Created commit with message: $commit_msg"
  fi
fi

# Remote configuration
remote_name=origin
has_origin=false
if git remote get-url "$remote_name" >/dev/null 2>&1; then
  has_origin=true
  echo "Remote '$remote_name' -> $(git remote get-url $remote_name)"
else
  echo "No remote named '$remote_name' configured."
fi

read -r -p "Add or update remote '$remote_name'? (enter URL to set, or leave empty to keep existing): " remote_url
if [[ -n "$remote_url" ]]; then
  if $has_origin; then
    git remote set-url $remote_name "$remote_url"
    echo "Updated remote '$remote_name' to $remote_url"
  else
    git remote add $remote_name "$remote_url"
    echo "Added remote '$remote_name' -> $remote_url"
  fi
fi

# Fetch and show divergence
if git remote get-url $remote_name >/dev/null 2>&1; then
  echo "Fetching from $remote_name..."
  git fetch $remote_name --prune
  remote_branch_exists=false
  branch_name=$(git branch --show-current)
  if git ls-remote --heads $remote_name "$branch_name" | grep -q refs/heads; then
    remote_branch_exists=true
  fi
  if $remote_branch_exists; then
    echo "Remote branch $remote_name/$branch_name exists. Showing differences (remote..local):"
    git log --oneline $remote_name/$branch_name..HEAD || true
  else
    echo "Remote branch $remote_name/$branch_name does not exist yet."
  fi
fi

# Push
read -r -p "Push current branch '$(git branch --show-current)' to remote '$remote_name'? [Y/n]: " do_push
do_push=${do_push:-Y}
if [[ "$do_push" =~ ^([yY][eE][sS]|[yY])$ ]]; then
  # Default: push normally. If remote has different history, recommend fetch+merge or force-with-lease.
  push_cmd=(git push -u $remote_name "$(git branch --show-current)")
  echo "About to run: ${push_cmd[*]}"
  read -r -p "Proceed with normal push? [Y/n]: " proceed_push
  proceed_push=${proceed_push:-Y}
  if [[ "$proceed_push" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    if "${push_cmd[@]}"; then
      echo "Push succeeded."
    else
      echo "Push failed. You may have diverging remote history."
      echo "Options:"
      echo "  1) Pull and merge: git pull --no-rebase $remote_name $(git branch --show-current)"
      echo "  2) Rebase onto remote: git pull --rebase $remote_name $(git branch --show-current)"
      echo "  3) Force update (safe variant): git push --force-with-lease $remote_name $(git branch --show-current)"
      read -r -p "Choose 1/2/3 or 'q' to quit: " resolution
      if [[ "$resolution" == "1" ]]; then
        git pull --no-rebase $remote_name $(git branch --show-current)
        git push -u $remote_name $(git branch --show-current)
      elif [[ "$resolution" == "2" ]]; then
        git pull --rebase $remote_name $(git branch --show-current)
        git push -u $remote_name $(git branch --show-current)
      elif [[ "$resolution" == "3" ]]; then
        read -r -p "Are you sure? This rewrites history on remote. Type 'I understand' to proceed: " confirm_force
        if [[ "$confirm_force" == "I understand" ]]; then
          git push --force-with-lease $remote_name $(git branch --show-current)
        else
          echo "Aborting force push."
        fi
      else
        echo "Aborting push resolution."
      fi
    fi
  else
    echo "Push canceled by user."
  fi
else
  echo "User chose not to push. Exiting."
fi

# Final verification instructions
echo "\nVerification commands you can run locally:"
echo " git remote show $remote_name"
echo " git ls-remote --heads $remote_name"
echo " git log --oneline $remote_name/$(git branch --show-current)..HEAD || true"

echo "Done."
